name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Set env
      run: go env -w GO111MODULE=off
      
    - name: Set env
      run: set GOARCH=amd64

    - name: Get goversioninfo
      run: go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo
      
    - name: Install goversioninfo
      run: go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo

    - name: Go Generate
      run: go generate

    - name: Build
      run: go build

    - name: Test
      run: go test
