name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Set env
      run: go env -w GO111MODULE=off
      
    - name: Set env
      run: set GOARCH=amd64

    - name: Build
      run: go build

    - name: Test
      run: go test
      
    - name: ls
      run: ls -la
